## 01 Data cleaning and preprocessing

This notebook serves as a data cleaning pipeline for the clustering project.

In [ ]:
import pandas as pd

df = pd.read_csv('/Users/andrejsebo/Projects/clustering-project/data/raw/data.txt', sep = '\t')

df.head

<bound method NDFrame.head of         id  reg  vb hinc hmem hint fixline hcar  sex  agecat  ...  q16#30  \
0        1   21   4   14    4    1       1    1    1       5  ...       0
1        2   21   4   14    4    1       1    1    2       5  ...       1
2        3   42   4   14    2    2       2    1    2       6  ...       0
3        4   42   4   14    2    2       2    1    1       6  ...       0
4        5   62   4   14    2    1       2    1    2       6  ...       0
...    ...  ...  ..  ...  ...  ...     ...  ...  ...     ...  ...     ...
2884  2885   72   2   14    5    1       1    1    2       3  ...       0
2885  2886   52   2   15    4    1       1    1    2       4  ...       0
2886  2887   52   5   17    3    1       1    1    2       2  ...       0
2887  2888   21   3   13    6    1       1    2    2       4  ...       0
2888  2889   21   3   13    6    1       1    2    1       3  ...       0

      q16#31  q16#32  q16#33 q16#34  q16#35  q16#36  q16#37  q16#38  q16#39
0          0       0       0      0       0       0       0       1       0
1          1       0       0      0       0       0       0       0       0
2          0       0       0      0       0       0       0       0       0
3          0       0       0      0       0       0       0       0       0
4          0       0       0      1       0       0       0       1       0
...      ...     ...     ...    ...     ...     ...     ...     ...     ...
2884       0       0       1      0       1       0       0       1       0
2885       1       0       1      0       0       0       0       0       0
2886       0       1       1      0       1       1       1       1       1
2887       1       0       0      0       0       0       0       1       0
2888       0       0       0      0       0       0       0       0       0

[2889 rows x 46 columns]>

In [20]:
df_new = df.drop(columns= ['reg', 'vb', 'hinc', 'hmem', 'hint', 'fixline', 'hcar', 'sex', 'agecat', 'marits', 'red', 'empst', 'hhead', 'pinc', 'sim', 'seg_ls'])

df_new.head()

,id,q16#11,q16#12,q16#13,q16#14,q16#15,q16#16,q16#17,q16#18,q16#19,...,q16#30,q16#31,q16#32,q16#33,q16#34,q16#35,q16#36,q16#37,q16#38,q16#39
0,1,0,0,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,1,0
1,2,0,0,0,0,0,1,0,0,1,...,1,1,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

Since the dataset contains many columns that are not relevant for our clustering analysis, we will drop them to simplify our dataset and focus on the most important features.

We move on to setting id as the index, now the old dataframe remains floating in the memory, the python garbage collector will eventually clean it up as it sees no vars are pointing to it.

In [21]:
df_new = df_new.set_index('id')
df_new.head()

,q16#11,q16#12,q16#13,q16#14,q16#15,q16#16,q16#17,q16#18,q16#19,q16#20,...,q16#30,q16#31,q16#32,q16#33,q16#34,q16#35,q16#36,q16#37,q16#38,q16#39
id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,1,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,1,0,0,1,0,...,1,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

Let's do some data validation now. The plan is to check whether we only go 0's or 1's for all questions and all observations. Then we check for missing values and for obs that only contain either 0's or 1's.

In [27]:
df_new.isin([0, 1]).all().all()

row_sums = df_new.sum(axis=1)
print(row_sums)

#row_sums.value_counts()

id
1        5
2        6
3        1
4        5
5        7
        ..
2885     9
2886     4
2887    11
2888     8
2889     2
Length: 2889, dtype: int64

In [28]:
row_sums = df_new.sum(axis=1)
print(row_sums)

#row_sums.value_counts()

id
1        5
2        6
3        1
4        5
5        7
        ..
2885     9
2886     4
2887    11
2888     8
2889     2
Length: 2889, dtype: int64

In [34]:
id_to_drop = row_sums[(row_sums < 3) | (row_sums > 17)].index
print(id_to_drop)
df_cleaned = df_new.drop(index=id_to_drop)
print(df_new.shape)
print(df_cleaned.shape)

Index([   3,   10,   25,   26,   32,   33,   35,   42,   49,   60,
       ...
       2779, 2784, 2800, 2807, 2814, 2827, 2833, 2843, 2872, 2889],
      dtype='int64', name='id', length=577)
(2889, 29)
(2312, 29)

Okay so this would be the end of data loading, formatting and cleaning. The only thing left to do is to save and freeze this final dataset for the next steps in the project. We will save it as a csv file in the data/processed folder. We will also save it as a pickle file, which is a binary format that preserves the data types and structure of the dataframe, making it faster to load and use in future steps of the project.

In [35]:
df_final = df_cleaned.to_csv('/Users/andrejsebo/Projects/clustering-project/data/processed/data_cleaned.csv', index=True)

df_final_pickle = df_cleaned.to_pickle('/Users/andrejsebo/Projects/clustering-project/data/processed/data_cleaned.pkl')